name: Build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:    
  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
